name=NocShield
version=1.0.0
author=Muhammad Ikhwan Fathulloh <muhammadikhwanfathulloh17@gmail.com>
maintainer=Nocturnailed Community <nocturnailed.team@gmail.com>
sentence=Modular network security simulation for ESP32
paragraph=NocShield brings network security simulations to microcontrollers. It offers a modular architecture and dynamic memory allocation suited for resource-constrained platforms, helping you simulate offensive and defensive network operations.
category=Device Control
url=https://github.com/Nocturnailed-Community/NocShield
architectures=esp32
includes=NocShield.h
